image: ghcr.io/cirruslabs/android-sdk:35

stages:
  - build
  - lint

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  DEBIAN_FRONTEND: "noninteractive"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - chmod +x ./gradlew
  - ./gradlew --version

build_debug:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - app/build/outputs/apk/debug/

lint_debug:
  stage: lint
  script:
    - ./gradlew lintDebug --stacktrace
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - app/build/reports/
