image: eclipse-temurin:17-jdk

stages:
  - build
  - lint

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - chmod +x ./gradlew
  - apt-get update -qq
  - apt-get install -y -qq wget unzip
  - mkdir -p /sdk/cmdline-tools
  - wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
  - unzip -q cmdline-tools.zip -d /sdk/cmdline-tools
  - mv /sdk/cmdline-tools/cmdline-tools /sdk/cmdline-tools/latest
  - export ANDROID_HOME=/sdk
  - export ANDROID_SDK_ROOT=/sdk
  - yes | /sdk/cmdline-tools/latest/bin/sdkmanager --licenses
  - /sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
  - echo "sdk.dir=/sdk" > local.properties

build_debug:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - app/build/outputs/apk/debug/*.apk

lint_debug:
  stage: lint
  script:
    - ./gradlew lintDebug
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - app/build/reports/lint-results-debug.html
